// frontend/src/app/pages/admin/bills.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BillService } from '../../services/bill.service';
import { UserService } from '../../services/user.service';
import { AppLayoutComponent } from '../../components/layout/app-layout/app-layout.component';

@Component({
  selector: 'app-admin-bills',
  standalone: true,
  imports: [CommonModule, FormsModule, AppLayoutComponent],
  templateUrl: './bills.component.html',
  styles: []
})
export class BillsComponent implements OnInit {
  bills: any[] = [];
  consumers: any[] = [];
  loading = true;
  showModal = false;
  error = '';
  saving = false;
  filterStatus = '';
  cycleResult: any = null;
  
  months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  
  form: any = {
    userId: '',
    previousReading: '',
    currentReading: '',
    billingPeriod: { month: new Date().getMonth() + 1, year: new Date().getFullYear() },
  };

  constructor(
    public billService: BillService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    Promise.all([
      this.billService.listAll({ status: this.filterStatus }).toPromise(),
      this.userService.list({ limit: 200 }).toPromise()
    ]).then(([billData, userData]) => {
      this.bills = billData.bills || [];
      this.consumers = userData.users || [];
    }).catch(err => {
      console.error('Failed to load bills', err);
    }).finally(() => {
      this.loading = false;
    });
  }

  handleGenerate(e: Event): void {
    e.preventDefault();
    this.error = '';
    this.saving = true;
    this.billService.generate(this.form.userId, {
      previousReading: Number(this.form.previousReading),
      currentReading: Number(this.form.currentReading),
      billingPeriod: this.form.billingPeriod,
    }).subscribe({
      next: () => {
        this.showModal = false;
        this.load();
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to generate bill';
        this.saving = false;
      },
      complete: () => {
        this.saving = false;
      }
    });
  }

  handleExport(): void {
    this.billService.exportCsv().subscribe({
      next: (blob) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `energi-bills-${Date.now()}.csv`;
        a.click();
        URL.revokeObjectURL(url);
      },
      error: () => alert('Export failed')
    });
  }

  handleRunCycle(): void {
    if (!confirm('Are you sure you want to run the automated billing cycle? This will parse the database and generate bills for unbilled consumers.')) return;
    
    // Defaulting to current month/year for the simulation cycle
    const month = new Date().getMonth() + 1;
    const year = new Date().getFullYear();
    
    this.billService.runCycle(month, year).subscribe({
      next: (res) => {
        this.cycleResult = res;
        this.load();
      },
      error: (err) => alert(err.error?.error || 'Auto-Billing cycle failed.')
    });
  }

  formatAmount(paise: number): string {
    return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }
}

<app-app-layout>
  <div class="page-header flex-between">
    <div>
      <h1>Bills</h1>
      <p>Generate and manage electricity bills</p>
    </div>
    <div class="flex gap-2">
      <select id="statusFilter" class="form-input" style="width: auto;" [(ngModel)]="filterStatus" (change)="load()" name="statusFilter">
        <option value="">All Status</option>
        <option value="UNPAID">Unpaid</option>
        <option value="PAID">Paid</option>
        <option value="DISPUTED">Disputed</option>
        <option value="WAIVED">Waived</option>
      </select>
      <button class="btn btn-secondary" (click)="handleExport()">⬇ Export CSV</button>
      <button class="btn btn-secondary" (click)="handleRunCycle()">⚡ Run Cycle</button>
      <button id="generateBillBtn" class="btn btn-primary" (click)="showModal = true">+ Generate Bill</button>
    </div>
  </div>
  <div *ngIf="cycleResult" class="card mb-6 animate-in" style="background: linear-gradient(135deg, rgba(16,185,129,0.1), rgba(124,58,237,0.05)); border: 1px solid rgba(16,185,129,0.3);">
    <div class="flex-between mb-4">
      <div class="flex gap-3">
        <div class="mark" style="background: var(--color-success); padding: 8px; border-radius: 8px; color: white;">⚡</div>
        <div>
          <h3 style="font-size: 16px;">Billing Cycle Complete</h3>
          <p class="text-sm">Summary of automated run</p>
        </div>
      </div>
      <button class="btn btn-secondary btn-sm" (click)="cycleResult = null">✕ Close</button>
    </div>
    
    <div class="grid-3 mb-4">
      <div class="stat-card" style="padding: 12px 16px;">
        <div class="stat-label">Generated</div>
        <div class="stat-value" style="font-size: 20px;">{{ cycleResult.success }}</div>
      </div>
      <div class="stat-card" style="padding: 12px 16px; border-color: rgba(239,68,68,0.2);">
        <div class="stat-label">Skipped/Failed</div>
        <div class="stat-value" style="font-size: 20px;">{{ cycleResult.failed }}</div>
      </div>
      <div class="stat-card" style="padding: 12px 16px;">
        <div class="stat-label">Total Users</div>
        <div class="stat-value" style="font-size: 20px;">{{ cycleResult.total }}</div>
      </div>
    </div>

    <div *ngIf="cycleResult.sampleCalculation" class="card" style="background: rgba(0,0,0,0.2); border-color: var(--color-border);">
      <h4 class="text-xs mb-2" style="text-transform: uppercase; color: var(--color-primary-light);">Sample Calculation: {{ cycleResult.sampleCalculation.consumer }}</h4>
      <div class="flex-between text-sm mb-1">
        <span>Units Consumed</span>
        <span class="font-bold">{{ cycleResult.sampleCalculation.units }} kWh</span>
      </div>
      <div *ngFor="let step of cycleResult.sampleCalculation.breakdown" class="flex-between text-xs text-muted mb-1">
        <span>{{ step.description }}</span>
        <span>{{ formatAmount(step.amountInPaise) }}</span>
      </div>
      <div class="flex-between mt-2 pt-2" style="border-top: 1px solid var(--color-border);">
        <span class="font-bold uppercase text-xs">Total Bill Amount</span>
        <span class="amount">{{ formatAmount(cycleResult.sampleCalculation.total) }}</span>
      </div>
    </div>
  </div>

  <div *ngIf="loading" class="flex-center" style="height: 200px;">
    <div class="spinner"></div>
  </div>

  <ng-container *ngIf="!loading">
    <div *ngIf="bills.length === 0" class="empty-state">
      <div class="icon">🧾</div>
      <h3>No bills found</h3>
      <p>Generate bills by entering meter readings</p>
    </div>

    <div *ngIf="bills.length > 0" class="card" style="padding: 0;">
      <div class="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>Consumer</th>
              <th>Period</th>
              <th>Units</th>
              <th>Amount</th>
              <th>Due</th>
              <th>Status</th>
              <th>PDF</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let b of bills">
              <td>
                <div style="font-weight: 500;">{{ b.userId?.name || '—' }}</div>
                <div class="text-muted">{{ b.userId?.consumerId }}</div>
              </td>
              <td>{{ b.billingPeriod?.month }}/{{ b.billingPeriod?.year }}</td>
              <td>{{ b.unitsConsumed }} kWh</td>
              <td><span class="amount">{{ formatAmount(b.totalInPaise) }}</span></td>
              <td class="text-muted">{{ b.dueDate | date:'dd/MM/yyyy' }}</td>
              <td><span class="badge" [ngClass]="'badge-' + b.status">{{ b.status }}</span></td>
              <td>
                <a [href]="billService.pdfUrl(b._id)" target="_blank" rel="noreferrer" class="btn btn-secondary btn-sm">📄 PDF</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </ng-container>

  <!-- Modal -->
  <div *ngIf="showModal" class="modal-overlay" (click)="showModal = false">
    <div class="modal" (click)="$event.stopPropagation()">
      <h2>Generate Bill</h2>
      <div *ngIf="error" class="alert alert-error">{{ error }}</div>
      <form (submit)="handleGenerate($event)">
        <div class="form-group">
          <label class="form-label">Select Consumer</label>
          <select id="billConsumer" class="form-select" [(ngModel)]="form.userId" name="userId" required>
            <option value="">Choose consumer...</option>
            <option *ngFor="let c of consumers" [value]="c._id">{{ c.name }} ({{ c.consumerId }})</option>
          </select>
        </div>
        <div class="grid-2">
          <div class="form-group">
            <label class="form-label">Month</label>
            <select class="form-select" [(ngModel)]="form.billingPeriod.month" name="month" required>
              <option *ngFor="let m of months; let i = index" [value]="i + 1">{{ m }}</option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-label">Year</label>
            <input type="number" class="form-input" [(ngModel)]="form.billingPeriod.year" name="year" required />
          </div>
        </div>
        <div class="grid-2">
          <div class="form-group">
            <label class="form-label">Previous Reading (kWh)</label>
            <input id="prevReading" type="number" class="form-input" placeholder="e.g. 1200" [(ngModel)]="form.previousReading" name="previousReading" required min="0" />
          </div>
          <div class="form-group">
            <label class="form-label">Current Reading (kWh)</label>
            <input id="currReading" type="number" class="form-input" placeholder="e.g. 1350" [(ngModel)]="form.currentReading" name="currentReading" required min="0" />
          </div>
        </div>
        <div *ngIf="form.previousReading !== '' && form.currentReading !== '' && +form.currentReading >= +form.previousReading" class="alert alert-success">
          Units consumed: <strong>{{ +form.currentReading - +form.previousReading }} kWh</strong>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" (click)="showModal = false">Cancel</button>
          <button id="saveBillBtn" type="submit" class="btn btn-primary" [disabled]="saving">
            {{ saving ? 'Generating...' : 'Generate Bill' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</app-app-layout>

// frontend-react-backup/src/pages/admin/Bills.jsx
import { useState, useEffect } from 'react';
import { AppLayout } from '../../components/layout/AppLayout.jsx';
import { billService, userService } from '../../services/index.js';

const formatAmount = (p) => `₹${(p / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
const now = new Date();

export default function AdminBills() {
  const [bills, setBills] = useState([]);
  const [consumers, setConsumers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [filterStatus, setFilterStatus] = useState('');
  const [form, setForm] = useState({
    userId: '',
    previousReading: '',
    currentReading: '',
    billingPeriod: { month: now.getMonth() + 1, year: now.getFullYear() },
  });

  const load = async () => {
    setLoading(true);
    try {
      const [{ data: billData }, { data: userData }] = await Promise.all([
        billService.listAll({ status: filterStatus }),
        userService.list({ limit: 200 }),
      ]);
      setBills(billData.bills || []);
      setConsumers(userData.users || []);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, [filterStatus]);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setError('');
    setSaving(true);
    try {
      await billService.generate(form.userId, {
        previousReading: Number(form.previousReading),
        currentReading: Number(form.currentReading),
        billingPeriod: form.billingPeriod,
      });
      setShowModal(false);
      load();
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate bill');
    } finally { setSaving(false); }
  };

  const handleExport = async () => {
    try {
      const { data } = await billService.exportCsv();
      const url = URL.createObjectURL(new Blob([data]));
      const a = document.createElement('a');
      a.href = url;
      a.download = `energi-bills-${Date.now()}.csv`;
      a.click();
    } catch (err) { alert('Export failed'); }
  };

  return (
    <AppLayout>
      <div className="page-header flex-between">
        <div>
          <h1>Bills</h1>
          <p>Generate and manage electricity bills</p>
        </div>
        <div className="flex gap-2">
          <select id="statusFilter" className="form-input" style={{ width: 'auto' }} value={filterStatus}
            onChange={e => setFilterStatus(e.target.value)}>
            <option value="">All Status</option>
            <option value="UNPAID">Unpaid</option>
            <option value="PAID">Paid</option>
            <option value="DISPUTED">Disputed</option>
            <option value="WAIVED">Waived</option>
          </select>
          <button className="btn btn-secondary" onClick={handleExport}>⬇ Export CSV</button>
          <button id="generateBillBtn" className="btn btn-primary" onClick={() => setShowModal(true)}>+ Generate Bill</button>
        </div>
      </div>

      {loading ? (
        <div className="flex-center" style={{ height: 200 }}><div className="spinner" /></div>
      ) : bills.length === 0 ? (
        <div className="empty-state">
          <div className="icon">🧾</div>
          <h3>No bills found</h3>
          <p>Generate bills by entering meter readings</p>
        </div>
      ) : (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Consumer</th>
                  <th>Period</th>
                  <th>Units</th>
                  <th>Amount</th>
                  <th>Due</th>
                  <th>Status</th>
                  <th>PDF</th>
                </tr>
              </thead>
              <tbody>
                {bills.map(b => (
                  <tr key={b._id}>
                    <td>
                      <div style={{ fontWeight: 500 }}>{b.userId?.name || '—'}</div>
                      <div className="text-muted">{b.userId?.consumerId}</div>
                    </td>
                    <td>{b.billingPeriod?.month}/{b.billingPeriod?.year}</td>
                    <td>{b.unitsConsumed} kWh</td>
                    <td><span className="amount">{formatAmount(b.totalInPaise)}</span></td>
                    <td className="text-muted">{new Date(b.dueDate).toLocaleDateString('en-IN')}</td>
                    <td><span className={`badge badge-${b.status}`}>{b.status}</span></td>
                    <td>
                      <a href={billService.pdfUrl(b._id)} target="_blank" rel="noreferrer"
                        className="btn btn-secondary btn-sm">📄 PDF</a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h2>Generate Bill</h2>
            {error && <div className="alert alert-error">{error}</div>}
            <form onSubmit={handleGenerate}>
              <div className="form-group">
                <label className="form-label">Select Consumer</label>
                <select id="billConsumer" className="form-select" value={form.userId}
                  onChange={e => setForm(f => ({ ...f, userId: e.target.value }))} required>
                  <option value="">Choose consumer...</option>
                  {consumers.map(c => (
                    <option key={c._id} value={c._id}>{c.name} ({c.consumerId})</option>
                  ))}
                </select>
              </div>
              <div className="grid-2">
                <div className="form-group">
                  <label className="form-label">Month</label>
                  <select className="form-select"
                    value={form.billingPeriod.month}
                    onChange={e => setForm(f => ({ ...f, billingPeriod: { ...f.billingPeriod, month: Number(e.target.value) } }))}>
                    {Array.from({ length: 12 }, (_, i) => (
                      <option key={i + 1} value={i + 1}>{new Date(0, i).toLocaleString('en-IN', { month: 'long' })}</option>
                    ))}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Year</label>
                  <input type="number" className="form-input" value={form.billingPeriod.year}
                    onChange={e => setForm(f => ({ ...f, billingPeriod: { ...f.billingPeriod, year: Number(e.target.value) } }))} required />
                </div>
              </div>
              <div className="grid-2">
                <div className="form-group">
                  <label className="form-label">Previous Reading (kWh)</label>
                  <input id="prevReading" type="number" className="form-input" placeholder="e.g. 1200"
                    value={form.previousReading} onChange={e => setForm(f => ({ ...f, previousReading: e.target.value }))} required min="0" />
                </div>
                <div className="form-group">
                  <label className="form-label">Current Reading (kWh)</label>
                  <input id="currReading" type="number" className="form-input" placeholder="e.g. 1350"
                    value={form.currentReading} onChange={e => setForm(f => ({ ...f, currentReading: e.target.value }))} required min="0" />
                </div>
              </div>
              {form.previousReading && form.currentReading && Number(form.currentReading) >= Number(form.previousReading) && (
                <div className="alert alert-success">
                  Units consumed: <strong>{Number(form.currentReading) - Number(form.previousReading)} kWh</strong>
                </div>
              )}
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
                <button id="saveBillBtn" type="submit" className="btn btn-primary" disabled={saving}>
                  {saving ? 'Generating...' : 'Generate Bill'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </AppLayout>
  );
}
