// frontend-react-backup/src/pages/admin/Dashboard.jsx
import { useState, useEffect } from 'react';
import { AppLayout } from '../../components/layout/AppLayout.jsx';
import { billService } from '../../services/index.js';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

const formatAmount = (paise) => `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

export default function AdminDashboard() {
  const [analytics, setAnalytics] = useState(null);
  const [recentBills, setRecentBills] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const [{ data: analyticsData }, { data: billsData }] = await Promise.all([
          billService.analytics(),
          billService.listAll({ limit: 5 }),
        ]);
        setAnalytics(analyticsData);
        setRecentBills(billsData.bills || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  // Dummy chart data for visualization
  const chartData = [
    { month: 'Nov', collected: 420000, pending: 80000 },
    { month: 'Dec', collected: 380000, pending: 120000 },
    { month: 'Jan', collected: 510000, pending: 60000 },
    { month: 'Feb', collected: 460000, pending: 90000 },
    { month: 'Mar', collected: 530000, pending: 45000 },
    { month: 'Apr', collected: analytics?.totalCollectedInPaise || 0, pending: analytics?.totalPendingInPaise || 0 },
  ];

  return (
    <AppLayout>
      <div className="page-header">
        <h1>Dashboard</h1>
        <p>Overview of your billing operations</p>
      </div>

      {loading ? (
        <div className="flex-center" style={{ height: 200 }}><div className="spinner" /></div>
      ) : (
        <>
          <div className="stats-grid">
            <div className="stat-card">
              <span className="stat-icon">💰</span>
              <div className="stat-label">Total Collected</div>
              <div className="stat-value">{formatAmount(analytics?.totalCollectedInPaise || 0)}</div>
            </div>
            <div className="stat-card">
              <span className="stat-icon">⏳</span>
              <div className="stat-label">Pending</div>
              <div className="stat-value" style={{ color: 'var(--color-warning)' }}>
                {formatAmount(analytics?.totalPendingInPaise || 0)}
              </div>
            </div>
            <div className="stat-card">
              <span className="stat-icon">🔴</span>
              <div className="stat-label">Overdue</div>
              <div className="stat-value" style={{ color: 'var(--color-danger)' }}>
                {formatAmount(analytics?.totalOverdueInPaise || 0)}
              </div>
            </div>
            <div className="stat-card">
              <span className="stat-icon">📄</span>
              <div className="stat-label">Total Bills</div>
              <div className="stat-value">{analytics?.billCount || 0}</div>
            </div>
          </div>

          {/* Chart */}
          <div className="card mb-6">
            <h3 style={{ marginBottom: 24, fontWeight: 600 }}>Collections Overview</h3>
            <ResponsiveContainer width="100%" height={200}>
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="collected" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#7C3AED" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#7C3AED" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <XAxis dataKey="month" tick={{ fill: '#9CA3AF', fontSize: 12 }} axisLine={false} tickLine={false} />
                <YAxis hide />
                <Tooltip
                  contentStyle={{ background: '#1A1A2E', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 8, fontSize: 12 }}
                  formatter={(v) => formatAmount(v)}
                />
                <Area type="monotone" dataKey="collected" stroke="#7C3AED" fill="url(#collected)" strokeWidth={2} name="Collected" />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          {/* Recent Bills */}
          <div className="card">
            <div className="flex-between mb-4">
              <h3 style={{ fontWeight: 600 }}>Recent Bills</h3>
              <a href="/admin/bills" className="btn btn-secondary btn-sm">View All</a>
            </div>
            {recentBills.length === 0 ? (
              <div className="empty-state">
                <div className="icon">🧾</div>
                <h3>No bills yet</h3>
                <p>Generate your first bill from the Bills section</p>
              </div>
            ) : (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>Consumer</th>
                      <th>Period</th>
                      <th>Amount</th>
                      <th>Due Date</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recentBills.map(bill => (
                      <tr key={bill._id}>
                        <td>{bill.userId?.name || '—'}<br /><span className="text-muted">{bill.userId?.consumerId}</span></td>
                        <td>{bill.billingPeriod?.month}/{bill.billingPeriod?.year}</td>
                        <td><span className="amount">{formatAmount(bill.totalInPaise)}</span></td>
                        <td className="text-muted">{new Date(bill.dueDate).toLocaleDateString('en-IN')}</td>
                        <td><span className={`badge badge-${bill.status}`}>{bill.status}</span></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}
    </AppLayout>
  );
}

// frontend/src/app/pages/admin/dashboard.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { BillService } from '../../services/bill.service';
import { AuthState, User } from '../../state/auth.state';
import { AppLayoutComponent } from '../../components/layout/app-layout/app-layout.component';
import { trigger, transition, style, animate, query, stagger } from '@angular/animations';
import { forkJoin, Subscription } from 'rxjs'; // Added Subscription for cleanup
import { Chart, registerables } from 'chart.js';

Chart.register(...registerables);

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, AppLayoutComponent],
  templateUrl: './dashboard.component.html',
  animations: [
    trigger('fadeInUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(20px)' }),
        animate('0.6s cubic-bezier(0.34, 1.56, 0.64, 1)', style({ opacity: 1, transform: 'translateY(0)' }))
      ])
    ]),
    trigger('staggerList', [
      transition(':enter', [
        query('.stagger-item', [
          style({ opacity: 0, transform: 'translateY(15px)' }),
          stagger(100, [
            animate('0.4s ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
          ])
        ], { optional: true })
      ])
    ])
  ]
})
export class DashboardComponent implements OnInit, OnDestroy {
  @ViewChild('statsChart') statsChart!: ElementRef<HTMLCanvasElement>;
  
  analytics: any = null;
  user: User | null = null;
  history: any[] = [];
  recentBills: any[] = [];
  loading = true;
  chart: any;
  private sub = new Subscription(); // To prevent memory leaks

  constructor(
    private billService: BillService,
    private authState: AuthState
  ) {}

  ngOnInit(): void {
    this.sub.add(this.authState.user$.subscribe(u => this.user = u));
    
    this.loadDashboardData();
  }

  loadDashboardData(): void {
    this.loading = true;
    forkJoin({
      analytics: this.billService.analytics(),
      bills: this.billService.listAll({ limit: 5 }),
      history: this.billService.getHistory()
    }).subscribe({
      next: (res) => {
        this.analytics = res.analytics;
        this.recentBills = res.bills?.bills || [];
        this.history = res.history || [];
        
        // Safety Guard: Only init chart if we have history data and the view is ready
        if (this.history.length > 0) {
          setTimeout(() => this.initChart(), 100);
        }
      },
      error: (err) => {
        console.error('Failed to load dashboard data', err);
        this.loading = false;
      },
      complete: () => {
        this.loading = false;
      }
    });
  }

  initChart(): void {
    // Permanent Fix 1: Check if canvas exists and history has items
    if (!this.statsChart || !this.history.length) return;

    const ctx = this.statsChart.nativeElement.getContext('2d');
    if (!ctx) return;

    // Destroy existing chart if it exists (prevents ghosting/memory leaks)
    if (this.chart) {
      this.chart.destroy();
    }

    const labels = this.history.map(h => `${h._id.month}/${h._id.year}`);
    const collectedData = this.history.map(h => (h.collected || 0) / 100);
    const pendingData = this.history.map(h => (h.pending || 0) / 100);

    const gradient = ctx.createLinearGradient(0, 0, 0, 300);
    gradient.addColorStop(0, 'rgba(124, 58, 237, 0.4)');
    gradient.addColorStop(1, 'rgba(124, 58, 237, 0)');

    this.chart = new Chart(ctx, {
      type: 'line',
      data: {
        labels,
        datasets: [
          {
            label: 'Collected (₹)',
            data: collectedData,
            borderColor: '#7C3AED',
            backgroundColor: gradient,
            fill: true,
            tension: 0.4,
            pointBackgroundColor: '#7C3AED',
            pointBorderColor: '#fff',
            pointHoverRadius: 6
          },
          {
            label: 'Pending (₹)',
            data: pendingData,
            borderColor: '#F59E0B',
            borderDash: [5, 5],
            fill: false,
            tension: 0.4
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'top',
            labels: { color: '#94a3b8', font: { size: 12 } }
          }
        },
        scales: {
          y: {
            beginAtZero: true,
            grid: { color: 'rgba(255,255,255,0.05)' },
            ticks: { 
              color: '#64748b',
              callback: (value) => '₹' + value 
            }
          },
          x: {
            grid: { display: false },
            ticks: { color: '#64748b' }
          }
        }
      }
    });
  }

  ngOnDestroy(): void {
    if (this.chart) this.chart.destroy();
    this.sub.unsubscribe();
  }

  formatAmount(paise: number): string {
    if (!paise && paise !== 0) return '₹0.00';
    return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }
}
<app-app-layout>
  <div class="page-header" [@fadeInUp]>
    <h1>Welcome back, {{ user?.name || 'Admin' }}</h1>
    <p>Here's what's happening with your energy network today.</p>
  </div>

  <div *ngIf="loading" class="flex-center" style="height: 400px; flex-direction: column; gap: 1rem;">
    <div class="spinner"></div>
    <p class="text-muted">Syncing energy data...</p>
  </div>

  <ng-container *ngIf="!loading">
    <div class="stats-grid" [@staggerList]>
      <div class="stat-card stagger-item">
        <span class="stat-icon">💰</span>
        <div class="stat-label">Total Collected</div>
        <div class="stat-value">{{ formatAmount(analytics?.totalCollectedInPaise || 0) }}</div>
      </div>
      <div class="stat-card stagger-item">
        <span class="stat-icon">⏳</span>
        <div class="stat-label">Pending</div>
        <div class="stat-value" style="color: var(--color-warning);">
          {{ formatAmount(analytics?.totalPendingInPaise || 0) }}
        </div>
      </div>
      <div class="stat-card stagger-item">
        <span class="stat-icon">🔴</span>
        <div class="stat-label">Overdue</div>
        <div class="stat-value" style="color: var(--color-danger);">
          {{ formatAmount(analytics?.totalOverdueInPaise || 0) }}
        </div>
      </div>
      <div class="stat-card stagger-item">
        <span class="stat-icon">📄</span>
        <div class="stat-label">Total Bills</div>
        <div class="stat-value">{{ analytics?.billCount || 0 }}</div>
      </div>
    </div>

    <div class="card mb-6" [@fadeInUp]>
      <h3 style="margin-bottom: 24px; font-weight: 600;">Collections Overview</h3>
      
      <div *ngIf="history && history.length > 0; else noChartData" class="chart-container" style="height: 300px; position: relative;">
        <canvas #statsChart></canvas>
      </div>

      <ng-template #noChartData>
        <div class="flex-center" style="height: 300px; flex-direction: column; text-align: center; background: rgba(255,255,255,0.02); border-radius: 12px; border: 1px dashed rgba(255,255,255,0.1);">
          <div style="font-size: 2rem; margin-bottom: 1rem;">📊</div>
          <h4 style="color: var(--color-text-muted);">No Trend Data Yet</h4>
          <p class="text-muted" style="max-width: 300px;">Collections data will appear here once you've completed your first billing cycle.</p>
        </div>
      </ng-template>
    </div>

    <div class="card" [@fadeInUp]>
      <div class="flex-between mb-4">
        <h3 style="font-weight: 600;">Recent Bills</h3>
        <a routerLink="/admin/bills" class="btn btn-secondary btn-sm" *ngIf="recentBills.length > 0">View All</a>
      </div>
      
      <div *ngIf="recentBills.length === 0" class="empty-state">
        <div class="icon">🧾</div>
        <h3>No bills yet</h3>
        <p>Generate your first bill from the Bills section</p>
        <button routerLink="/admin/bills" class="btn btn-primary btn-sm" style="margin-top: 1rem;">Create Bill</button>
      </div>

      <div *ngIf="recentBills.length > 0" class="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>Consumer</th>
              <th>Period</th>
              <th>Amount</th>
              <th>Due Date</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let bill of recentBills">
              <td>
                <div style="font-weight: 500;">{{ bill.userId?.name || '—' }}</div>
                <div class="text-muted" style="font-size: 0.8rem;">{{ bill.userId?.consumerId }}</div>
              </td>
              <td>{{ bill.billingPeriod?.month }}/{{ bill.billingPeriod?.year }}</td>
              <td><span class="amount" style="font-weight: 600;">{{ formatAmount(bill.totalInPaise) }}</span></td>
              <td class="text-muted">{{ bill.dueDate | date:'dd/MM/yyyy' }}</td>
              <td><span class="badge" [ngClass]="'badge-' + (bill.status | lowercase)">{{ bill.status }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </ng-container>
</app-app-layout>
