// frontend/src/app/components/layout/app-layout/app-layout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { AuthState, User, Org } from '../../../state/auth.state';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-app-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './app-layout.component.html',
  styles: []
})
export class AppLayoutComponent implements OnInit {
  user: User | null = null;
  org: Org | null = null;

  constructor(
    private authState: AuthState,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authState.user$.subscribe(user => this.user = user);
    this.authState.org$.subscribe(org => this.org = org);
  }

  handleLogout(): void {
    this.authService.logout().subscribe({
      next: () => {
        this.router.navigate(['/login']);
      },
      error: (err) => {
        console.error('Logout failed', err);
        this.router.navigate(['/login']);
      }
    });
  }
}

<div class="app-layout">
  <aside class="sidebar">
    <div class="sidebar-logo">
      <div class="logo-mark">E</div>
      <span class="logo-text">{{ org?.name || 'EnergI' }}</span>
    </div>

    <!-- Admin Nav -->
    <nav class="sidebar-nav" *ngIf="user?.role === 'ADMIN'">
      <p class="nav-section-label">Overview</p>
      <a routerLink="/admin/dashboard" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">📊</span> Dashboard
      </a>
      <p class="nav-section-label">Management</p>
      <a routerLink="/admin/users" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">👥</span> Consumers
      </a>
      <a routerLink="/admin/tariff" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">⚡</span> Tariff Config
      </a>
      <a routerLink="/admin/bills" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">🧾</span> Bills
      </a>
      <a routerLink="/admin/disputes" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">⚠️</span> Disputes
      </a>
    </nav>

    <!-- Consumer Nav -->
    <nav class="sidebar-nav" *ngIf="user?.role === 'CONSUMER'">
      <p class="nav-section-label">My Account</p>
      <a routerLink="/consumer/dashboard" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">🏠</span> Dashboard
      </a>
      <a routerLink="/consumer/bills" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">🧾</span> My Bills
      </a>
      <a routerLink="/consumer/disputes" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">📋</span> Disputes
      </a>
    </nav>

    <div style="padding: 16px 12px; border-top: 1px solid var(--color-border); margin-top: auto;">
      <div style="padding: 10px 12px; border-radius: 8px; background: var(--color-surface-2); margin-bottom: 8px;">
        <div style="fontSize: 13px; fontWeight: 600;">{{ user?.name }}</div>
        <div style="fontSize: 11px; color: var(--color-text-muted);">{{ user?.role }} · {{ user?.consumerId }}</div>
      </div>
      <button class="nav-item" (click)="handleLogout()" style="color: var(--color-danger); width: 100%;">
        <span class="nav-icon">🚪</span> Logout
      </button>
    </div>
  </aside>

  <main class="main-content animate-in">
    <ng-content></ng-content>
  </main>
</div>

// frontend-react-backup/src/components/layout/AppLayout.jsx
import { NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';

const AdminNav = () => (
  <nav className="sidebar-nav">
    <p className="nav-section-label">Overview</p>
    <NavLink to="/admin/dashboard" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">📊</span> Dashboard
    </NavLink>
    <p className="nav-section-label">Management</p>
    <NavLink to="/admin/users" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">👥</span> Consumers
    </NavLink>
    <NavLink to="/admin/tariff" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">⚡</span> Tariff Config
    </NavLink>
    <NavLink to="/admin/bills" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">🧾</span> Bills
    </NavLink>
    <NavLink to="/admin/disputes" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">⚠️</span> Disputes
    </NavLink>
  </nav>
);

const ConsumerNav = () => (
  <nav className="sidebar-nav">
    <p className="nav-section-label">My Account</p>
    <NavLink to="/consumer/dashboard" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">🏠</span> Dashboard
    </NavLink>
    <NavLink to="/consumer/bills" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">🧾</span> My Bills
    </NavLink>
    <NavLink to="/consumer/disputes" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
      <span className="nav-icon">📋</span> Disputes
    </NavLink>
  </nav>
);

export const AppLayout = ({ children }) => {
  const { user, org, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  return (
    <div className="app-layout">
      <aside className="sidebar">
        <div className="sidebar-logo">
          <div className="logo-mark">E</div>
          <span className="logo-text">{org?.name || 'EnergI'}</span>
        </div>

        {user?.role === 'ADMIN' ? <AdminNav /> : <ConsumerNav />}

        <div style={{ padding: '16px 12px', borderTop: '1px solid var(--color-border)', marginTop: 'auto' }}>
          <div style={{ padding: '10px 12px', borderRadius: '8px', background: 'var(--color-surface-2)', marginBottom: '8px' }}>
            <div style={{ fontSize: '13px', fontWeight: 600 }}>{user?.name}</div>
            <div style={{ fontSize: '11px', color: 'var(--color-text-muted)' }}>{user?.role} · {user?.consumerId}</div>
          </div>
          <button className="nav-item" onClick={handleLogout} style={{ color: 'var(--color-danger)', width: '100%' }}>
            <span className="nav-icon">🚪</span> Logout
          </button>
        </div>
      </aside>

      <main className="main-content">
        {children}
      </main>
    </div>
  );
};
