// frontend/src/app/pages/consumer/dashboard.component.ts
import { Component, OnInit, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { BillService } from '../../services/bill.service';
import { PaymentService } from '../../services/payment.service';
import { AuthState, User } from '../../state/auth.state';
import { AppLayoutComponent } from '../../components/layout/app-layout/app-layout.component';
import { Chart, registerables } from 'chart.js';
import { trigger, transition, style, animate, query, stagger } from '@angular/animations';
import { forkJoin } from 'rxjs';

Chart.register(...registerables);

@Component({
  selector: 'app-consumer-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, AppLayoutComponent],
  templateUrl: './dashboard.component.html',
  animations: [
    trigger('fadeInUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(20px)' }),
        animate('0.6s cubic-bezier(0.34, 1.56, 0.64, 1)', style({ opacity: 1, transform: 'translateY(0)' }))
      ])
    ]),
    trigger('staggerList', [
      transition(':enter', [
        query('.stagger-item', [
          style({ opacity: 0, transform: 'translateY(15px)' }),
          stagger(100, [
            animate('0.4s ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
          ])
        ], { optional: true })
      ])
    ])
  ],
  styles: []
})
export class DashboardComponent implements OnInit {
  @ViewChild('usageChart') usageChart!: ElementRef<HTMLCanvasElement>;

  user: User | null = null;
  bills: any[] = [];
  history: any[] = [];
  loading = true;
  paying: string | null = null;
  chart: any;

  constructor(
    private authState: AuthState,
    public billService: BillService,
    private paymentService: PaymentService
  ) {}

  ngOnInit(): void {
    this.authState.user$.subscribe(user => this.user = user);
    
    forkJoin({
      bills: this.billService.listMy({ limit: 3 }),
      history: this.billService.getMyHistory()
    }).subscribe({
      next: (res) => {
        this.bills = res.bills.bills || [];
        this.history = res.history;
        setTimeout(() => this.initChart(), 0);
      },
      error: (err) => console.error(err),
      complete: () => this.loading = false
    });
  }

  initChart(): void {
    if (!this.usageChart) return;
    const ctx = this.usageChart.nativeElement.getContext('2d');
    if (!ctx) return;

    const labels = this.history.map(h => `${h._id.month}/${h._id.year}`);
    const data = this.history.map(h => h.units);

    this.chart = new Chart(ctx, {
      type: 'line',
      data: {
        labels,
        datasets: [{
          label: 'kWh Consumed',
          data: data,
          borderColor: '#10B981', // Success green for consumer
          backgroundColor: 'rgba(16, 185, 129, 0.1)',
          fill: true,
          tension: 0.4,
          pointRadius: 4,
          pointHoverRadius: 6
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
          y: { 
            beginAtZero: true, 
            grid: { color: 'rgba(255,255,255,0.05)' },
            ticks: { color: '#64748b' }
          },
          x: { 
            grid: { display: false },
            ticks: { color: '#64748b' }
          }
        }
      }
    });
  }

  get latestBill(): any {
    return this.bills[0];
  }

  get isOverdue(): boolean {
    if (!this.latestBill || this.latestBill.status !== 'UNPAID') return false;
    return new Date(this.latestBill.dueDate) < new Date();
  }

  handlePay(billId: string): void {
    this.paying = billId;
    this.paymentService.checkout(billId).subscribe({
      next: (data) => {
        window.location.href = data.url;
      },
      error: (err) => {
        alert(err.error?.error || 'Payment failed to initialize');
        this.paying = null;
      }
    });
  }

  formatAmount(paise: number): string {
    return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }
}

<app-app-layout>
  <div class="page-header" [@fadeInUp]>
    <h1>Welcome, {{ (user?.name?.split(' ') || [])[0] }} 👋</h1>
    <p>Consumer ID: <strong>{{ user?.consumerId }}</strong> · Meter: <strong>{{ user?.meterNumber || 'Not assigned' }}</strong></p>
  </div>

  <div *ngIf="loading" class="flex-center" style="height: 200px;">
    <div class="spinner"></div>
  </div>

  <ng-container *ngIf="!loading">
    <!-- Current Bill Hero Card -->
    <div *ngIf="latestBill" class="card mb-6" [@fadeInUp] [style.background]="isOverdue ? 'linear-gradient(135deg, rgba(239,68,68,0.1), rgba(239,68,68,0.05))' : 'linear-gradient(135deg, rgba(124,58,237,0.15), rgba(167,139,250,0.05))'" [style.borderColor]="isOverdue ? 'rgba(239,68,68,0.3)' : 'rgba(124,58,237,0.3)'">
      <div class="flex-between">
        <div>
          <div class="text-muted text-sm">Current Bill — {{ latestBill.billingPeriod?.month }}/{{ latestBill.billingPeriod?.year }}</div>
          <div [style.color]="isOverdue ? 'var(--color-danger)' : 'var(--color-primary-light)'" style="font-size: 48px; font-weight: 800; letter-spacing: -2px; line-height: 1.1; margin: 8px 0;">
            {{ formatAmount(latestBill.totalInPaise) }}
          </div>
          <div class="text-muted">{{ latestBill.unitsConsumed }} kWh consumed</div>
          <div class="mt-2">
            <span class="badge" [ngClass]="'badge-' + latestBill.status">{{ latestBill.status }}</span>
            <span *ngIf="isOverdue" style="font-size: 12px; color: var(--color-danger); margin-left: 8px;">⚠️ Overdue since {{ latestBill.dueDate | date:'dd/MM/yyyy' }}</span>
            <span *ngIf="!isOverdue && latestBill.status === 'UNPAID'" class="text-muted text-sm" style="margin-left: 8px;">Due {{ latestBill.dueDate | date:'dd/MM/yyyy' }}</span>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; gap: 10px; align-items: flex-end;">
          <div *ngIf="latestBill.status === 'DISPUTED'" class="alert alert-error" style="margin: 0; padding: 6px 12px; font-size: 11px;">
            ⚠️ Payment frozen under review
          </div>
          <button *ngIf="latestBill.status === 'UNPAID'" id="payNowBtn" class="btn btn-primary btn-lg" (click)="handlePay(latestBill._id)" [disabled]="paying === latestBill._id || latestBill.status === 'DISPUTED'">
            {{ paying === latestBill._id ? 'Redirecting...' : (latestBill.status === 'DISPUTED' ? 'Payment Frozen' : '💳 Pay Now') }}
          </button>
          <a [href]="billService.pdfUrl(latestBill._id)" target="_blank" rel="noreferrer" class="btn btn-secondary btn-sm">
            📄 Download PDF
          </a>
        </div>
      </div>
    </div>

    <div *ngIf="!latestBill" class="card mb-6 empty-state">
      <div class="icon">🎉</div>
      <h3>No bills yet</h3>
      <p>Your bills will appear here once generated</p>
    </div>

    <!-- Consumption Trend Chart -->
    <div class="card mb-6" [@fadeInUp]>
      <h3 style="margin-bottom: 24px; font-weight: 600;">Energy Usage Trend</h3>
      <div class="chart-container" style="height: 250px; position: relative;">
        <canvas #usageChart></canvas>
      </div>
      <div *ngIf="history.length === 0" class="flex-center" style="height: 100px;">
        <p class="text-muted">Usage trends will appear here after your first few bills.</p>
      </div>
    </div>

    <!-- Recent Bills -->
    <div *ngIf="bills.length > 0" class="card" [@fadeInUp]>
      <div class="flex-between mb-4">
        <h3 style="font-weight: 600;">Recent Bills</h3>
        <a routerLink="/consumer/bills" class="btn btn-secondary btn-sm">View All</a>
      </div>
      <div class="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>Period</th>
              <th>Units</th>
              <th>Amount</th>
              <th>Due Date</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let b of bills">
              <td>{{ b.billingPeriod?.month }}/{{ b.billingPeriod?.year }}</td>
              <td>{{ b.unitsConsumed }} kWh</td>
              <td><span class="amount">{{ formatAmount(b.totalInPaise) }}</span></td>
              <td class="text-muted">{{ b.dueDate | date:'dd/MM/yyyy' }}</td>
              <td><span class="badge" [ngClass]="'badge-' + b.status">{{ b.status }}</span></td>
              <td>
                <button *ngIf="b.status === 'UNPAID'" class="btn btn-primary btn-sm" (click)="handlePay(b._id)" [disabled]="paying === b._id">
                  Pay
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </ng-container>
</app-app-layout>

// frontend-react-backup/src/pages/consumer/Dashboard.jsx
import { useState, useEffect } from 'react';
import { AppLayout } from '../../components/layout/AppLayout.jsx';
import { billService, paymentService } from '../../services/index.js';
import { useAuth } from '../../context/AuthContext.jsx';

const formatAmount = (p) => `₹${(p / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

export default function ConsumerDashboard() {
  const { user } = useAuth();
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [paying, setPaying] = useState(null);

  useEffect(() => {
    billService.listMy({ limit: 3 })
      .then(({ data }) => setBills(data.bills || []))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const latestBill = bills[0];
  const isOverdue = latestBill && latestBill.status === 'UNPAID' && new Date(latestBill.dueDate) < new Date();

  const handlePay = async (billId) => {
    setPaying(billId);
    try {
      const { data } = await paymentService.checkout(billId);
      window.location.href = data.url;
    } catch (err) {
      alert(err.response?.data?.error || 'Payment failed to initialize');
      setPaying(null);
    }
  };

  return (
    <AppLayout>
      <div className="page-header">
        <h1>Welcome, {user?.name?.split(' ')[0]} 👋</h1>
        <p>Consumer ID: <strong>{user?.consumerId}</strong> · Meter: <strong>{user?.meterNumber || 'Not assigned'}</strong></p>
      </div>

      {loading ? (
        <div className="flex-center" style={{ height: 200 }}><div className="spinner" /></div>
      ) : (
        <>
          {/* Current Bill Hero Card */}
          {latestBill ? (
            <div className="card mb-6" style={{
              background: isOverdue
                ? 'linear-gradient(135deg, rgba(239,68,68,0.1), rgba(239,68,68,0.05))'
                : 'linear-gradient(135deg, rgba(124,58,237,0.15), rgba(167,139,250,0.05))',
              borderColor: isOverdue ? 'rgba(239,68,68,0.3)' : 'rgba(124,58,237,0.3)',
            }}>
              <div className="flex-between">
                <div>
                  <div className="text-muted text-sm">Current Bill — {latestBill.billingPeriod?.month}/{latestBill.billingPeriod?.year}</div>
                  <div style={{ fontSize: 48, fontWeight: 800, letterSpacing: -2, color: isOverdue ? 'var(--color-danger)' : 'var(--color-primary-light)', lineHeight: 1.1, margin: '8px 0' }}>
                    {formatAmount(latestBill.totalInPaise)}
                  </div>
                  <div className="text-muted">{latestBill.unitsConsumed} kWh consumed</div>
                  <div className="mt-2">
                    <span className={`badge badge-${latestBill.status}`}>{latestBill.status}</span>
                    {isOverdue && <span style={{ fontSize: 12, color: 'var(--color-danger)', marginLeft: 8 }}>⚠️ Overdue since {new Date(latestBill.dueDate).toLocaleDateString('en-IN')}</span>}
                    {!isOverdue && latestBill.status === 'UNPAID' && <span className="text-muted text-sm" style={{ marginLeft: 8 }}>Due {new Date(latestBill.dueDate).toLocaleDateString('en-IN')}</span>}
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10, alignItems: 'flex-end' }}>
                  {latestBill.status === 'UNPAID' && (
                    <button id="payNowBtn" className="btn btn-primary btn-lg" onClick={() => handlePay(latestBill._id)} disabled={paying === latestBill._id}>
                      {paying === latestBill._id ? 'Redirecting...' : '💳 Pay Now'}
                    </button>
                  )}
                  <a href={billService.pdfUrl(latestBill._id)} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm">
                    📄 Download PDF
                  </a>
                </div>
              </div>
            </div>
          ) : (
            <div className="card mb-6 empty-state">
              <div className="icon">🎉</div>
              <h3>No bills yet</h3>
              <p>Your bills will appear here once generated</p>
            </div>
          )}

          {/* Recent Bills */}
          {bills.length > 0 && (
            <div className="card">
              <div className="flex-between mb-4">
                <h3 style={{ fontWeight: 600 }}>Recent Bills</h3>
                <a href="/consumer/bills" className="btn btn-secondary btn-sm">View All</a>
              </div>
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>Period</th>
                      <th>Units</th>
                      <th>Amount</th>
                      <th>Due Date</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {bills.map(b => (
                      <tr key={b._id}>
                        <td>{b.billingPeriod?.month}/{b.billingPeriod?.year}</td>
                        <td>{b.unitsConsumed} kWh</td>
                        <td><span className="amount">{formatAmount(b.totalInPaise)}</span></td>
                        <td className="text-muted">{new Date(b.dueDate).toLocaleDateString('en-IN')}</td>
                        <td><span className={`badge badge-${b.status}`}>{b.status}</span></td>
                        <td>
                          {b.status === 'UNPAID' && (
                            <button className="btn btn-primary btn-sm" onClick={() => handlePay(b._id)} disabled={paying === b._id}>
                              Pay
                            </button>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </AppLayout>
  );
}
