// frontend-react-backup/src/pages/consumer/Bills.jsx
import { useState, useEffect } from 'react';
import { AppLayout } from '../../components/layout/AppLayout.jsx';
import { billService, paymentService, disputeService } from '../../services/index.js';

const formatAmount = (p) => `₹${(p / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

export default function ConsumerBills() {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [paying, setPaying] = useState(null);
  const [disputeModal, setDisputeModal] = useState(null);
  const [disputeReason, setDisputeReason] = useState('');
  const [disputeSaving, setDisputeSaving] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const { data } = await billService.listMy();
      setBills(data.bills || []);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  const handlePay = async (billId) => {
    setPaying(billId);
    try {
      const { data } = await paymentService.checkout(billId);
      window.location.href = data.url;
    } catch (err) {
      alert(err.response?.data?.error || 'Payment failed');
      setPaying(null);
    }
  };

  const handleDispute = async (e) => {
    e.preventDefault();
    setDisputeSaving(true);
    try {
      await disputeService.raise(disputeModal._id, disputeReason);
      setDisputeModal(null);
      setDisputeReason('');
      load();
    } catch (err) {
      alert(err.response?.data?.error || 'Failed to raise dispute');
    } finally { setDisputeSaving(false); }
  };

  return (
    <AppLayout>
      <div className="page-header">
        <h1>My Bills</h1>
        <p>Complete billing history</p>
      </div>

      {loading ? (
        <div className="flex-center" style={{ height: 200 }}><div className="spinner" /></div>
      ) : bills.length === 0 ? (
        <div className="empty-state">
          <div className="icon">📄</div>
          <h3>No bills yet</h3>
          <p>Your bill history will appear here</p>
        </div>
      ) : (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Period</th>
                  <th>Units Consumed</th>
                  <th>Amount</th>
                  <th>Due Date</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {bills.map(b => (
                  <tr key={b._id}>
                    <td style={{ fontWeight: 500 }}>{b.billingPeriod?.month}/{b.billingPeriod?.year}</td>
                    <td>{b.unitsConsumed} kWh</td>
                    <td><span className="amount">{formatAmount(b.totalInPaise)}</span></td>
                    <td className="text-muted">{new Date(b.dueDate).toLocaleDateString('en-IN')}</td>
                    <td><span className={`badge badge-${b.status}`}>{b.status}</span></td>
                    <td>
                      <div className="flex gap-2">
                        <a href={billService.pdfUrl(b._id)} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm">📄</a>
                        {b.status === 'UNPAID' && (
                          <>
                            <button className="btn btn-primary btn-sm" onClick={() => handlePay(b._id)} disabled={paying === b._id}>
                              {paying === b._id ? '...' : 'Pay'}
                            </button>
                            <button id={`disputeBtn-${b._id}`} className="btn btn-danger btn-sm" onClick={() => setDisputeModal(b)}>
                              Dispute
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {disputeModal && (
        <div className="modal-overlay" onClick={() => setDisputeModal(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h2>Raise Dispute</h2>
            <p className="text-muted mb-4">
              Bill for {disputeModal.billingPeriod?.month}/{disputeModal.billingPeriod?.year} — {formatAmount(disputeModal.totalInPaise)}
            </p>
            <form onSubmit={handleDispute}>
              <div className="form-group">
                <label className="form-label">Reason for dispute</label>
                <textarea id="disputeReason" className="form-input" style={{ minHeight: 100, resize: 'vertical' }}
                  placeholder="Describe the issue with this bill..."
                  value={disputeReason}
                  onChange={e => setDisputeReason(e.target.value)}
                  required minLength={20} />
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setDisputeModal(null)}>Cancel</button>
                <button id="submitDisputeBtn" type="submit" className="btn btn-danger" disabled={disputeSaving}>
                  {disputeSaving ? 'Submitting...' : 'Submit Dispute'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </AppLayout>
  );
}

// frontend/src/app/pages/consumer/bills.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BillService } from '../../services/bill.service';
import { PaymentService } from '../../services/payment.service';
import { DisputeService } from '../../services/dispute.service';
import { AppLayoutComponent } from '../../components/layout/app-layout/app-layout.component';

@Component({
  selector: 'app-consumer-bills',
  standalone: true,
  imports: [CommonModule, FormsModule, AppLayoutComponent],
  templateUrl: './bills.component.html',
  styles: []
})
export class BillsComponent implements OnInit {
  bills: any[] = [];
  loading = true;
  paying: string | null = null;
  disputeModal: any = null;
  disputeReason: string = '';
  disputeSaving = false;

  constructor(
    public billService: BillService,
    private paymentService: PaymentService,
    private disputeService: DisputeService
  ) {}

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.billService.listMy().subscribe({
      next: (data) => {
        this.bills = data.bills || [];
      },
      error: (err) => console.error(err),
      complete: () => {
        this.loading = false;
      }
    });
  }

  handlePay(billId: string): void {
    this.paying = billId;
    this.paymentService.checkout(billId).subscribe({
      next: (data) => {
        window.location.href = data.url;
      },
      error: (err) => {
        alert(err.error?.error || 'Payment failed');
        this.paying = null;
      }
    });
  }

  handleDispute(e: Event): void {
    e.preventDefault();
    this.disputeSaving = true;
    this.disputeService.raise(this.disputeModal._id, this.disputeReason).subscribe({
      next: () => {
        this.disputeModal = null;
        this.disputeReason = '';
        this.load();
      },
      error: (err) => {
        alert(err.error?.error || 'Failed to raise dispute');
      },
      complete: () => {
        this.disputeSaving = false;
      }
    });
  }

  formatAmount(paise: number): string {
    return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }
}

<app-app-layout>
  <div class="page-header">
    <h1>My Bills</h1>
    <p>Complete billing history</p>
  </div>

  <div *ngIf="loading" class="flex-center" style="height: 200px;">
    <div class="spinner"></div>
  </div>

  <ng-container *ngIf="!loading">
    <div *ngIf="bills.length === 0" class="empty-state">
      <div class="icon">📄</div>
      <h3>No bills yet</h3>
      <p>Your bill history will appear here</p>
    </div>

    <div *ngIf="bills.length > 0" class="card" style="padding: 0;">
      <div class="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>Period</th>
              <th>Units Consumed</th>
              <th>Amount</th>
              <th>Due Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let b of bills">
              <td style="font-weight: 500;">{{ b.billingPeriod?.month }}/{{ b.billingPeriod?.year }}</td>
              <td>{{ b.unitsConsumed }} kWh</td>
              <td><span class="amount">{{ formatAmount(b.totalInPaise) }}</span></td>
              <td class="text-muted">{{ b.dueDate | date:'dd/MM/yyyy' }}</td>
              <td><span class="badge" [ngClass]="'badge-' + b.status">{{ b.status }}</span></td>
              <td>
                <div class="flex gap-2">
                  <a [href]="billService.pdfUrl(b._id)" target="_blank" rel="noreferrer" class="btn btn-secondary btn-sm">📄</a>
                  <ng-container *ngIf="b.status === 'UNPAID'">
                    <button class="btn btn-primary btn-sm" (click)="handlePay(b._id)" [disabled]="paying === b._id">
                      {{ paying === b._id ? '...' : 'Pay' }}
                    </button>
                    <button [id]="'disputeBtn-' + b._id" class="btn btn-danger btn-sm" (click)="disputeModal = b">
                      Dispute
                    </button>
                  </ng-container>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </ng-container>

  <!-- Modal -->
  <div *ngIf="disputeModal" class="modal-overlay" (click)="disputeModal = null">
    <div class="modal" (click)="$event.stopPropagation()">
      <h2>Raise Dispute</h2>
      <p class="text-muted mb-4">
        Bill for {{ disputeModal.billingPeriod?.month }}/{{ disputeModal.billingPeriod?.year }} — {{ formatAmount(disputeModal.totalInPaise) }}
      </p>
      <form (submit)="handleDispute($event)">
        <div class="form-group">
          <label class="form-label">Reason for dispute</label>
          <textarea id="disputeReason" class="form-input" style="min-height: 100px; resize: vertical;"
            placeholder="Describe the issue with this bill..."
            [(ngModel)]="disputeReason" name="disputeReason"
            required minlength="20"></textarea>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" (click)="disputeModal = null">Cancel</button>
          <button id="submitDisputeBtn" type="submit" class="btn btn-danger" [disabled]="disputeSaving">
            {{ disputeSaving ? 'Submitting...' : 'Submit Dispute' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</app-app-layout>
